import {
  IconDefinition,
  faBagel,
  faBowlChopsticks,
  faBowlChopsticksNoodles,
  faBowlHot,
  faBowlScoops,
  faBurger,
  faCake,
  faCakeSlice,
  faCheeseSwiss,
  faCoffeePot,
  faCookie,
  faCupcake,
  faDrumstick,
  faFalafel,
  faFish,
  faForkKnife,
  faHotdog,
  faIceCream,
  faMartiniGlass,
  faMeat,
  faPancakes,
  faPizzaSlice,
  faPotFood,
  faSandwich,
  faSteak,
  faSushi,
  faTaco,
} from '@fortawesome/pro-solid-svg-icons';

const cuisineIconMap: Record<string, IconDefinition> = {
  'American': faForkKnife,
  'American Breakfast': faCoffeePot,
  'Asian Innovative': faForkKnife,
  'Assorted': faForkKnife,
  'Australian': faForkKnife,
  'BBQ': faMeat,
  'Bagels': faBagel,
  'Bar': faMartiniGlass,
  'Beef Omakase': faForkKnife,
  'British': faForkKnife,
  'Brunch': faCoffeePot,
  'Burger': faBurger,
  'Cafe': faCake,
  'Cake': faCakeSlice,
  'Cape Malay': faForkKnife,
  'Cheese': faCheeseSwiss,
  'Chinese': faBowlChopsticks,
  'Chops': faSteak,
  'Confectionary': faCupcake,
  'Cookie': faCookie,
  'Dessert': faBowlScoops,
  'Eastern European': faForkKnife,
  'European': faForkKnife,
  'Falafel': faFalafel,
  'Fish & Chips': faFish,
  'French': faForkKnife,
  'Fried Chicken': faDrumstick,
  'Fusion': faForkKnife,
  'German': faForkKnife,
  'Gyoza': faBowlChopsticks,
  'Hot Dog': faHotdog,
  'Hungarian': faForkKnife,
  'Ice Cream': faIceCream,
  'Indian': faForkKnife,
  'Indonesian': faForkKnife,
  'Innovative': faForkKnife,
  'Italian': faForkKnife,
  'Japanese': faBowlChopsticks,
  'Japanese Curry': faBowlChopsticks,
  'Karaage': faBowlChopsticks,
  'Korean': faBowlChopsticks,
  'Korean Fusion': faBowlChopsticks,
  'Malaysian': faForkKnife,
  'Meatballs': faForkKnife,
  'Mexican': faTaco,
  'Middle Eastern': faForkKnife,
  'Moroccan': faForkKnife,
  'Nasi Kandar': faForkKnife,
  'Nikkei': faSushi,
  'Nordic': faForkKnife,
  'Omurice': faForkKnife,
  'Pad Kra Pow': faForkKnife,
  'Pancakes': faPancakes,
  'Pastrami': faSandwich,
  'Pizza': faPizzaSlice,
  'Ramen': faBowlChopsticksNoodles,
  'Schnitzel': faForkKnife,
  'Shabu Shabu/Sukiyaki': faBowlHot,
  'Slovakian': faForkKnife,
  'Soba': faBowlChopsticksNoodles,
  'South African': faForkKnife,
  'South American': faForkKnife,
  'Southeast Asian': faForkKnife,
  'Spanish': faForkKnife,
  'Steak': faSteak,
  'Sukiyaki': faPotFood,
  'Sushi': faSushi,
  'Swedish': faForkKnife,
  'Taffelspitz': faForkKnife,
  'Tapas': faForkKnife,
  'Thai': faForkKnife,
  'Tom Yum Kung': faBowlHot,
  'Tonkatsu': faMeat,
  'Udon': faBowlChopsticksNoodles,
  'Yakiniku': faMeat,
  'Yakitori': faMeat,
};

export default cuisineIconMap;